import {
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_BP5100DN,
  hp1,
  hp3,
  ricoh1,
  ricoh2,
} from "../assets/images/index";

import img from "./placamae1.png"

import "./style.css";

// =================== NavBarList Começa aqui ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Início",
    link: "/",
  },
  {
    _id: 1002,
    title: "Loja",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "Sobre",
    link: "/about",
  },
  {
    _id: 1004,
    title: "contate-nos",
    link: "contact",
  },
];
// =================== NavBarList Termina aqui ======================
// =================== Dados de Oferta Especial Começa aqui ============
export const SplOfferData = [];
// =================== Dados de Oferta Especial Termina aqui ==============

// =================== Itens de Paginação Começa aqui ===============

export const paginationItems = [
  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "Impressora PANTUM CP2200DW",
    price: "350.00",
    color: "Branco",
    badge: true,
    brand: "Pantum",
    des: "Impressora a laser PANTUM colorida - Funções: Impressão - Tecnologia de impressão: Laser - Formato de papel: A4 - Velocidade de impressão (Colorido/P&B): 24 ppm (A4) / 26 ppm (Carta) - Resolução de impressão: 600 x 600 dpi - Saída de papel: 100 páginas - Memória: Processador dual-core, 1 GHz - Impressão duplex: Automática - Tempo para a primeira impressão: Menos de 11s - Conectores: USB 2.0 de alta velocidade Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Sem fio - Dimensões: 411,2 x 394,1 x 243,7 mm - Peso: 16,1 kg - Cor: Branco",
    cat: "Impressora",
    pdf: pdf1,
    ficheTech: [
      { label: "Tecnologia", value: "Laser monocromático por eletrofotografia" },
      { label: "Velocidade de impressão", value: "22 ppm (A4)/23 ppm (Carta)" },
      { label: "Tempo para a primeira impressão", value: "Menos de 7,8s" },
      { label: "Ciclo de trabalho mensal máximo", value: "15.000 páginas" },
      { label: "Volume mensal recomendado", value: "700 páginas" },
      { label: "Modo duplex", value: "Máximo 1.200×1.200 dpi" },
      { label: "Impressora", value: "Máximo 1.2" },
      { label: "Vidro", value: "Máximo 1.2" },
    ],
  },
  {
    _id: "202",
    img: IMPRIMANTE_PANTUM_BM5100FDW,
    productName: "IMPRESSORA PANTUM BM5100FDW",
    price: "450.00",
    color: "Branco",
    badge: true,
    brand: "Pantum",
    des: "Pantum BM5100fdw Impressora a laser monocromática: Pantum BM5100fdw - Impressora: laser - multifuncional monocromática, formato A4, 4-em-1 com funções de impressão, cópia, digitalização e fax, velocidade de impressão de 40ppm, conexão LAN RJ45, Wi-Fi.",
    cat: "Impressora",
    pdf: pdf1,
    ficheTech: [
      { label: "Velocidade de impressão", value: "40ppm (A4)/42ppm (Carta)" },
      { label: "Tempo de saída da primeira página", value: "≤6,9 s" },
      { label: "Volume mensal recomendado", value: "750 a 4.000 páginas" },
      { label: "Resolução de impressão", value: "Máx. 1.200x1.200 dpi" },
      { label: "Linguagem de impressão", value: "PCL5e, PCL6, PS" },
      { label: "Velocidade do processador", value: "1,2 GHz" },
      { label: "Memória", value: "512 MB" },
      { label: "Painel de controle", value: "LCD 2 linhas || Tela sensível ao toque de 3,5 polegadas" },
      { label: "Impressão duplex automática", value: "Sim" },
      { label: "Outras funções de impressão", value: "Impressão de brochuras, impressão segura, impressão de disco USB compatível com AirPrint, Mopria, APP móvel (iOS/Android)" },
      { label: "Velocidade de cópia", value: "40ppm (A4)/42ppm (Carta)" },
      { label: "Tempo de saída da primeira cópia", value: "Bandeja: menos de 10 s ADF: menos de 11 s" },
    ],
  },
  {
    _id: "203",
    img: IMPRIMANTE_PANTUM_BP5100DN,
    productName: "IMPRESSORA PANTUM BP5100DN",
    price: "450.00",
    color: "Branco",
    badge: true,
    brand: "Pantum",
    des: "Impressora Monocromática Laser PANTUM BP5100DN: Funções de impressão - Capacidade de bandeja de papel 250 páginas - Formato de papel: A4 - Tecnologia de impressão Laser Monocromática - Velocidade de impressão Preto & Branco: Até 40 páginas por minuto em A4 - Resolução: 1.200 dpi - Memória: 512 MB - Conectividade Ethernet, USB 2.0 - Duplex automático - Pronta para rede: Impressão silenciosa - Dimensões: 364 x 344 x 257 mm - Peso: 9,3 kg - Garantia: 1 ano",
    cat: "Impressora",
    pdf: pdf1,
    ficheTech: [
      { label: "Velocidade de impressão", value: "40ppm (A4)/42ppm (Carta)" },
      { label: "Tempo de saída da primeira página", value: "≤6,9 s" },
      { label: "Volume mensal recomendado", value: "750 a 4.000 páginas" },
      { label: "Resolução de impressão", value: "Máx. 1.200x1.200 dpi" },
      { label: "Linguagem de impressão", value: "PCL5e, PCL6, PS" },
      { label: "Velocidade do processador", value: "1,2 GHz" },
      { label: "Memória", value: "512 MB" },
      { label: "Painel de controle", value: "LCD 2 linhas || Tela sensível ao toque de 3,5 polegadas" },
      { label: "Impressão duplex automática", value: "Sim" },
      { label: "Outras funções de impressão", value: "Impressão de brochuras, impressão segura, impressão de disco USB compatível com AirPrint, Mopria, APP móvel (iOS/Android)" },
      { label: "Velocidade de cópia", value: "40ppm (A4)/42ppm (Carta)" },
      { label: "Tempo de saída da primeira cópia", value: "Bandeja: menos de 10 s ADF: menos de 11 s" },
    ],
  },
  {
    _id: "2005",
    img: IMPRIMANTE_PANTUM_M6609N,
    productName: "IMPRESSORA PANTUM M6559N",
    price: "450.00",
    color: "Branco",
    badge: true,
    brand: "Pantum",
    des: "Impressora Laser 3-em-1 com toner recarregável PANTUM M6559N - Capacidade de impressão de até 1.600 páginas - Velocidade de impressão: 22 ppm (A4) / 23 ppm (Carta) - Resolução (impressão, cópia e digitalização): 1.200×1.200dpi - Tempo da primeira impressão: Menos de 7,8s - Conectividade: USB 2.0 de alta velocidade - Velocidade de cópia: 22 cpm (A4) / 23 cpm (Carta) - Capacidade do alimentador automático de documentos: 35 páginas - Entrada de papel: 150 páginas - Saída de papel: 100 páginas - Dimensões: 417 x 305 x 301 mm - Peso: 8,5 kg - Garantia de 1 ano",
    cat: "Impressora",
    pdf: pdf1,
    ficheTech: [
      { label: "Código GTIN", value: "M6559N" },
      { label: "Capacidade de impressão", value: "Até 1.600 páginas" },
      { label: "Função", value: "3 em 1" },
      { label: "Tecnologia", value: "Laser monocromático" },
    ],
  },



  // =================== imprimante hp =================

  {
    _id: "hp1",
    img: img,
    productName: "IMPRESSORA HP JATO DE TINTA HP SMART TANK 516 COLORIDA MFP 3 EM 1 A4 WIFI",
    price: "450.00",
    color: "Branco",
    badge: true,
    brand: "Hp",
    des: "Descrição: Impressora Jato de Tinta HP SMART TANK 516 3 em 1 Colorida 3YW70A - Função: Impressão, Cópia, Digitalização - Tecnologia de Impressão: Jato de Tinta - Velocidade de Impressão em Preto: Até 22 ppm - Velocidade de Impressão Colorida: Até 16 ppm - Resolução de Impressão Colorida: 1200x1200 dpi - Formato de Papel: A4 - Capacidade de Papel: 100 folhas - Ciclo de Trabalho (mensal, A4): Até 1000 páginas - Conectividade: USB 2.0 de alta velocidade, Wi-Fi, Bluetooth LE - Dimensões: 447 x 373 x 158 mm - Garantia: 1 ano",
    cat: "Impressora",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILIDADE", value: "Em estoque" },
      { label: "gtin", value: "3YW70A" },
      { label: "Marca", value: "HP" },
      { label: "Liquidação", value: "Não" },
      { label: "Tela", value: "LCD" },
      { label: "Tamanho da Tela (cm)", value: "Tela LCD 7 segmentos + ícone 5,08 cm (2 polegadas)" },
      { label: "Tela Touch", value: "Não" },
      { label: "Tecnologia de Impressão", value: "Jato de Tinta" },
      { label: "Funções", value: "Multifuncional" },
      { label: "Funcionalidades", value: "Impressão, Cópia, Digitalização" },
      { label: "Impressão", value: "Colorida" },
      { label: "Formatos", value: "A4" },
      { label: "Alimentação de Documentos", value: "Sim" },
      { label: "Velocidade de Impressão em Preto", value: "Até 22 ppm" },
      { label: "Velocidade de Impressão Colorida", value: "Até 16 ppm" },
      { label: "FAX", value: "Não" },
      { label: "Memória", value: "256 MB" },
      { label: "Qualidade de Impressão em Preto", value: "Até 1.200 x 1.200 ppp" },
      { label: "Qualidade de Impressão Colorida", value: "Até 4.800 x 1.200 ppp" },
      { label: "Resolução de Impressão Colorida", value: "1200x1200 dpi" },
      { label: "Impressão Frente e Verso", value: "Manual" },
      { label: "Tipo de Scanner", value: "Scanner Plano" },
      { label: "Conectividade", value: "USB 2.0, Wi-Fi" },
      { label: "Capacidade de Papel", value: "100 folhas" },
      { label: "Ciclo de Trabalho Mensal", value: "Até 1000 páginas" },
      { label: "Consumo Elétrico", value: "0,12 Watts (Desligada manualmente), 3,12 Watts (Pronta), 0,75 Watt (Espera)" },
      { label: "Gramatura", value: "75 g/m²" },
      { label: "Conteúdo da Embalagem", value: "Impressora HP Smart Tank 516, Garrafas de tinta: 3 x HP GT53XL (preto), 3 x HP GT52 (ciano, magenta e amarelo), Manual de precaução para tinta; Ficha de reembalagem e regulamentos RoH-EAC; Cabo de alimentação, Guia de instalação; Manual PT" },
      { label: "Peso", value: "5,14 kg" },
      { label: "Dimensões", value: "447 x 373 x 158 mm" },
      { label: "Cor", value: "Preto e Azul" },
      { label: "Garantia", value: "1 ano" }
    ]
  },

  {
    _id: "hp3",
    img: img,
    productName: "IMPRESSORA HP INK TANK WIRELESS 415 ALL-IN-ONE",
    price: "450.00",
    color: "Branco",
    badge: true,
    brand: "Hp",
    des: "Impressora com Reservatório de Tinta HP Ink Tank 315 - Funções: Impressão, Cópia, Digitalização - Formato de Papel: A4 - Tecnologia de Impressão: Jato de Tinta Térmico HP - Velocidade de Impressão: Até 19 ppm (Preto), Até 15 ppm (Colorido) - Resolução de Impressão: 1200 x 1200 dpi (Colorido), 4800 x 1200 dpi (Preto) - Velocidade de Cópia (A4, ISO): 6,5 cpm Preto; 2 cpm Colorido - Velocidade de Digitalização A4: Até 21 segundos - Impressão Frente e Verso Manual - Formatos de Arquivos para Digitalização: JPEG, TIFF, PDF, BMP, PNG - Velocidade do Processador: 360 MHz - Conectividade: USB - Dimensões: 525 x 310 x 158 mm - Peso: 4,67 kg - Garantia: 1 ano",
    cat: "Impressora",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILIDADE", value: "Em estoque" },
      { label: "gtin", value: "Z4B04A" },
      { label: "Marca", value: "HP" },
      { label: "Liquidação", value: "Não" },
      { label: "Tecnologia de Impressão", value: "Multifuncional Jato de Tinta" },
      { label: "Funções", value: "Multifuncional" },
      { label: "Impressão", value: "Colorida" },
      { label: "Memória", value: "Não" },
      { label: "FAX", value: "Não" },
      { label: "Funcionalidades", value: "Impressão, Cópia, Digitalização" },
      { label: "Alimentação de Documentos", value: "Sim" },
      { label: "Conectores", value: "1 porta USB 2.0 de alta velocidade" },
      { label: "Velocidade do Processador", value: "360 MHz" },
      { label: "Impressão Sem Borda", value: "Sim, até 210 x 297 mm (A4)" },
      { label: "Velocidade de Impressão em Preto", value: "Até 19 ppm" },
      { label: "Velocidade de Impressão Colorida", value: "Até 15 ppm" },
      { label: "Resolução de Impressão em Preto", value: "Até 1.200 x 1.200 DPI" },
      { label: "Resolução de Impressão Colorida", value: "Até 4.800 x 1.200 DPI" },
      { label: "Resolução de Impressão", value: "Até 1.200 x 1.200 DPI (Preto), Até 4.800 x 1.200 DPI (Colorido)" },
      { label: "Tipo de Scanner", value: "Scanner Plano" },
      { label: "Velocidade de Digitalização", value: "Até 21 segundos" },
      { label: "Resolução de Digitalização", value: "Até 1.200 x 1.200 ppp" },
      { label: "Resolução de Digitalização Otimizada", value: "Até 1.200 ppp" },
      { label: "Impressão Frente e Verso", value: "Manual" },
      { label: "Conectividade", value: "USB" },
      { label: "Formatos", value: "A4" },
      { label: "Primeira Página Impressa", value: "Preto: (A4, pronto) Velocidade: 14 s - Colorido (A4, pronto) Velocidade: 18 s" },
      { label: "Alimentação Elétrica", value: "Tensão de entrada: 220 a 240 V AC (+/- 10%), 50/60 Hz (+/- 3 Hz)" },
      { label: "Tipos de Papel Suportados", value: "Papel comum, papéis fotográficos HP, papel fosco para brochura HP ou papel profissional HP, papel fosco para apresentação HP, papel brilhante para brochura HP ou papel profissional HP, papéis fotográficos para jato de tinta, papéis foscos para jato de tinta, papéis brilhantes" },
      { label: "Consumo Elétrico", value: "10 W máximo, 0,07 W (Desligado manualmente), 2,1 W (Ativa), 0,88 W (Pronta), 0,1 W (Espera)" },
      { label: "Peso", value: "4,67 kg" },
      { label: "Dimensões", value: "525 x 310 x 158 mm" },
      { label: "Cor", value: "Preto e Branco" },
      { label: "Garantia", value: "1 ano" }
    ]
  },
  // =================== imprimante ricoh =================
  {
    _id: "ricoh1",
    img: img,
    productName: "IMPRIMENTE RICOH P501",
    price: "450.00",
    color: "Branco",
    badge: true,
    brand: "Ricoh",
    des: "Impressora com Reservatório Integrado HP Ink Tank 315 - Funções: Impressão, cópia, digitalização - Formato do Papel: A4 - Tecnologia de Impressão: jato de tinta térmico HP - Velocidade de Impressão: Até 19 ppm (Preto), Até 15 ppm (Cor) - Resolução de Impressão: 1200 x 1200 dpi (cor), 4800 x 1200 dpi (preto) - Velocidade de Cópia (A4, ISO): 6,5 cpm Preto; 2 cpm Cor - Velocidade de Digitalização A4: Até 21 segundos - Impressão Duplex Manual - Formatos de Arquivos para Digitalização: JPEG, TIFF, PDF, BMP, PNG - Velocidade do Processador: 360 MHz - Conectividade: USB - Dimensões: 525 x 310 x 158 mm - Peso: 4,67 kg - Garantia: 1 ano",
    cat: "Impressora",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILIDADE", "value": "Em estoque" },
      { label: "gtin", "value": "Z4B04A" },
      { label: "Marca", "value": "HP" },
      { label: "Desconto", "value": "Não" },
      { label: "Tecnologia de Impressão", "value": "Multifuncional Jato de Tinta" },
      { label: "Funções", "value": "Multifuncional" },
      { label: "Impressão", "value": "Cor" },
      { label: "Memória", "value": "Não" },
      { label: "FAX", "value": "Não" },
      { label: "Funcionalidades", "value": "Impressão, Cópia, Digitalização" },
      { label: "Carregamento de Documentos", "value": "Sim" },
      { label: "Conectores", "value": "1 porta USB 2.0 de alta velocidade" },
      { label: "Velocidade do Processador", "value": "360 MHz" },
      { label: "Impressão sem Borda", "value": "Sim, até 210 x 297 mm (A4)" },
      { label: "Velocidade de Impressão Preto", "value": "Até 19 ppm" },
      { label: "Velocidade de Impressão Cor", "value": "Até 15 ppm" },
      { label: "Resolução de Impressão Preto", "value": "Até 1 200 x 1 200 DPI" },
      { label: "Resolução de Impressão Cor", "value": "Até 4 800 x 1 200 DPI (cor)" },
      { label: "Resolução de Impressão", "value": "Até 1 200 x 1 200 DPI (preto), Até 4 800 x 1 200 DPI (cor)" },
      { label: "Tipo de Scanner", "value": "Scanner Plano" },
      { label: "Velocidade de Digitalização", "value": "Até 21 segundos" },
      { label: "Resolução de Digitalização", "value": "Até 1200 x 1200 dpi" },
      { label: "Resolução de Digitalização Otimizada", "value": "Até 1200 dpi" },
      { label: "Duplex", "value": "Manual" },
      { label: "Conectividade", "value": "USB" },
      { label: "Formatos", "value": "A4" },
      { label: "Primeira Página Impressa", "value": "Preto: (A4, pronto) Velocidade: 14 s - Cor (A4, pronto) Velocidade: 18 s" },
      { label: "Fonte de Alimentação", "value": "Tensão de entrada: 220 a 240 V AC (+/- 10 %), 50/60 Hz (+/- 3 Hz)" },
      { label: "Tipo de Papel Compatível", "value": "Papel comum, papéis fotográficos HP, papel fosco para brochura HP ou papel profissional HP, papel fosco para apresentação HP, papel brilhante para brochura HP ou papel profissional HP, papéis fotográficos jato de tinta, papéis foscos jato de tinta, papéis brilhantes" },
      { label: "Consumo de Energia", "value": "10 W máximo, 0,07 W (Desligado), 2,1 W (Em espera), 0,88 W (Em espera prolongada)" },
      { label: "Ciclo de Uso Mensal", "value": "A4: Até 1 000 páginas - Carta: Até 1 000 páginas" },
      { label: "Alimentação de Papel Padrão", "value": "Bandeja de alimentação de 60 folhas - Bandeja de saída de 25 folhas" },
      { label: "Tela Touch", "value": "Não" },
      { label: "Tipo de Tela", "value": "7 segmentos e ícone LCD" },
      { label: "Volume Mensal de Páginas Recomendado", "value": "400 a 800 (Até 1 000 páginas)" },
      { label: "Interfaces Padrão", "value": "1x porta USB 2.0 de alta velocidade" },
      { label: "Resolução Óptica", "value": "Até 1200 x 1200 dpi" },
      { label: "Gramatura", "value": "75 g/m²" },
      { label: "Conteúdo da Embalagem", "value": "HP Ink Tank 315, cartucho de tinta preta HP GT51 (90CC), cartucho de tinta ciano HP GT52 (70CC), cartucho de tinta magenta HP GT52 (70CC), cartucho de tinta amarela HP GT52 (70CC)" },
      { label: "Peso", "value": "4,67 kg" },
      { label: "Cor", "value": "Preto" },
      { label: "Dimensões", "value": "525 x 310 x 158 mm" },
      { label: "Garantia", "value": "1 ano" }
    ],
  },

  {
    _id: "ricoh2",
    img: img,
    productName: "IMPRIMENTE RICOH SP3710DN",
    price: "450.00",
    color: "Branco",
    badge: true,
    brand: "Ricoh",
    des: "Impressora com Reservatório Integrado HP Ink Tank 315 - Funções: Impressão, cópia, digitalização - Formato do Papel: A4 - Tecnologia de Impressão: jato de tinta térmico HP - Velocidade de Impressão: Até 19 ppm (Preto), Até 15 ppm (Cor) - Resolução de Impressão: 1200 x 1200 dpi (cor), 4800 x 1200 dpi (preto) - Velocidade de Cópia (A4, ISO): 6,5 cpm Preto; 2 cpm Cor - Velocidade de Digitalização A4: Até 21 segundos - Impressão Duplex Manual - Formatos de Arquivos para Digitalização: JPEG, TIFF, PDF, BMP, PNG - Velocidade do Processador: 360 MHz - Conectividade: USB - Dimensões: 525 x 310 x 158 mm - Peso: 4,67 kg - Garantia: 1 ano",
    cat: "Impressora",
    pdf: pdf1,
    ficheTech: [
      { label: "DISPONIBILIDADE", "value": "Em estoque" },
      { label: "gtin", "value": "Z4B04A" },
      { label: "Marca", "value": "HP" },
      { label: "Desconto", "value": "Não" },
      { label: "Tecnologia de Impressão", "value": "Multifuncional Jato de Tinta" },
      { label: "Funções", "value": "Multifuncional" },
      { label: "Impressão", "value": "Cor" },
      { label: "Memória", "value": "Não" },
      { label: "FAX", "value": "Não" },
      { label: "Funcionalidades", "value": "Impressão, Cópia, Digitalização" },
      { label: "Carregamento de Documentos", "value": "Sim" },
      { label: "Conectores", "value": "1 porta USB 2.0 de alta velocidade" },
      { label: "Velocidade do Processador", "value": "360 MHz" },
      { label: "Impressão sem Borda", "value": "Sim, até 210 x 297 mm (A4)" },
      { label: "Velocidade de Impressão Preto", "value": "Até 19 ppm" },
      { label: "Velocidade de Impressão Cor", "value": "Até 15 ppm" },
      { label: "Resolução de Impressão Preto", "value": "Até 1 200 x 1 200 DPI" },
      { label: "Resolução de Impressão Cor", "value": "Até 4 800 x 1 200 DPI (cor)" },
      { label: "Resolução de Impressão", "value": "Até 1 200 x 1 200 DPI (preto), Até 4 800 x 1 200 DPI (cor)" },
      { label: "Tipo de Scanner", "value": "Scanner Plano" },
      { label: "Velocidade de Digitalização", "value": "Até 21 segundos" },
      { label: "Resolução de Digitalização", "value": "Até 1200 x 1200 dpi" },
      { label: "Resolução de Digitalização Otimizada", "value": "Até 1200 dpi" },
      { label: "Duplex", "value": "Manual" },
      { label: "Conectividade", "value": "USB" },
      { label: "Formatos", "value": "A4" },
      { label: "Primeira Página Impressa", "value": "Preto: (A4, pronto) Velocidade: 14 s - Cor (A4, pronto) Velocidade: 18 s" },
      { label: "Fonte de Alimentação", "value": "Tensão de entrada: 220 a 240 V AC (+/- 10 %), 50/60 Hz (+/- 3 Hz)" },
      { label: "Tipo de Papel Compatível", "value": "Papel comum, papéis fotográficos HP, papel fosco para brochura HP ou papel profissional HP, papel fosco para apresentação HP, papel brilhante para brochura HP ou papel profissional HP, papéis fotográficos jato de tinta, papéis foscos jato de tinta, papéis brilhantes" },
      { label: "Consumo de Energia", "value": "10 W máximo, 0,07 W (Desligado), 2,1 W (Em espera), 0,88 W (Em espera prolongada)" },
      { label: "Ciclo de Uso Mensal", "value": "A4: Até 1 000 páginas - Carta: Até 1 000 páginas" },
      { label: "Alimentação de Papel Padrão", "value": "Bandeja de alimentação de 60 folhas - Bandeja de saída de 25 folhas" },
      { label: "Tela Touch", "value": "Não" },
      { label: "Tipo de Tela", "value": "7 segmentos e ícone LCD" },
      { label: "Volume Mensal de Páginas Recomendado", "value": "400 a 800 (Até 1 000 páginas)" },
      { label: "Interfaces Padrão", "value": "1x porta USB 2.0 de alta velocidade" },
      { label: "Resolução Óptica", "value": "Até 1200 x 1200 dpi" },
      { label: "Gramatura", "value": "75 g/m²" },
      { label: "Conteúdo da Embalagem", "value": "HP Ink Tank 315, cartucho de tinta preta HP GT51 (90CC), cartucho de tinta ciano HP GT52 (70CC), cartucho de tinta magenta HP GT52 (70CC), cartucho de tinta amarela HP GT52 (70CC)" },
      { label: "Peso", "value": "4,67 kg" },
      { label: "Cor", "value": "Preto" },
      { label: "Dimensões", "value": "525 x 310 x 158 mm" },
      { label: "Garantia", "value": "1 ano" }
    ],
  }
];
